
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have compressor to storage block recipes added.
	toStorageBlockMaterialBlacklist = []
	#The materials that should not have compressor to raw storage block recipes added.
	toRawStorageBlockMaterialBlacklist = []
	#The materials that should not have roller to plate recipes added.
	toPlateMaterialBlacklist = []
	#The materials that should not have hammer to plate recipes added.
	hammerToPlateMaterialBlacklist = []

