
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 7638016

[create]
	#The default byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[crossroads]
	#The byproduct material to output in Crossroads' Millstone.
	byproduct = "minecraft:sand"

[indreb]
	#The temperature required in the themal centrifuge.
	temperature = 1200

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "#forge:cobblestone/normal"

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

